package main

import (
	"bytes"
	"fmt"
	"os"

	"github.com/superfly/ltx"
)

func main() {
	if len(os.Args) == 4 && os.Args[1] == "--check" {
		if err := checkFixture(os.Args[2], os.Args[3]); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		return
	}
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: legacy_fixturegen [--check] <snapshot-zero|mixed> [path]")
		os.Exit(2)
	}
	spec, err := fixture(os.Args[1])
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(2)
	}
	if _, err := spec.WriteTo(os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func checkFixture(name, path string) error {
	spec, err := fixture(name)
	if err != nil {
		return err
	}
	var generated bytes.Buffer
	if _, err := spec.WriteTo(&generated); err != nil {
		return fmt.Errorf("generate %s: %w", name, err)
	}
	committed, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	if !bytes.Equal(generated.Bytes(), committed) {
		return fmt.Errorf("generated %s does not match %s", name, path)
	}
	return nil
}

func fixture(name string) (*ltx.FileSpec, error) {
	page1 := make([]byte, 512)
	switch name {
	case "snapshot-zero":
		pages := []ltx.PageSpec{{Header: ltx.PageHeader{Pgno: 1}, Data: page1}}
		return snapshot(pages), nil
	case "mixed":
		pages := []ltx.PageSpec{
			{Header: ltx.PageHeader{Pgno: 1}, Data: page1},
			{Header: ltx.PageHeader{Pgno: 2}, Data: xorshiftPage()},
		}
		return snapshot(pages), nil
	default:
		return nil, fmt.Errorf("unknown fixture %q", name)
	}
}

func snapshot(pages []ltx.PageSpec) *ltx.FileSpec {
	postApplyChecksum := ltx.ChecksumFlag
	for _, page := range pages {
		postApplyChecksum = ltx.ChecksumFlag |
			(postApplyChecksum ^ ltx.ChecksumPage(page.Header.Pgno, page.Data))
	}
	return &ltx.FileSpec{
		Header: ltx.Header{
			Version:  ltx.Version,
			PageSize: 512,
			Commit:   uint32(len(pages)),
			MinTXID:  1,
			MaxTXID:  1,
		},
		Pages:   pages,
		Trailer: ltx.Trailer{PostApplyChecksum: postApplyChecksum},
	}
}

func xorshiftPage() []byte {
	page := make([]byte, 512)
	state := uint32(0x9e3779b9)
	for index := range page {
		state ^= state << 13
		state ^= state >> 17
		state ^= state << 5
		page[index] = byte(state)
	}
	return page
}
